#!/usr/bin/env bash
# Verify a private vendor blob repository generated by import-vendor-blobs.sh.
set -euo pipefail

BASE_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/.." && pwd)
REPO_DIR="${1:-}"

usage() {
  echo "usage: $0 <private-vendor-blob-repo-dir>" >&2
}

if [ -z "$REPO_DIR" ] || [ ! -d "$REPO_DIR" ]; then
  usage
  exit 2
fi

for f in \
  BUILD.bazel \
  REPO.bazel \
  SHA256SUMS \
  bfw.img \
  pins.inputs.json \
  vendor_blobs.meta.json \
  was110_vendor_blobs.bazelrc \
  was110_vendor_blobs.env \
  was110_vendor_blobs.handoff.json; do
  [ -f "$REPO_DIR/$f" ] || { echo "missing $REPO_DIR/$f" >&2; exit 2; }
done
for f in bootcore.bin kernel.bin rootfs.img; do
  [ -f "$REPO_DIR/basic/$f" ] || { echo "missing $REPO_DIR/basic/$f" >&2; exit 2; }
done

command -v jq >/dev/null || { echo "jq required" >&2; exit 2; }
command -v sha256sum >/dev/null || { echo "sha256sum required" >&2; exit 2; }

(
  cd "$REPO_DIR"
  sha256sum -c SHA256SUMS
)

"$BASE_DIR/pins/verify.sh" \
  --pins "$REPO_DIR/pins.inputs.json" \
  --strict \
  "$REPO_DIR/bfw.img" \
  "$REPO_DIR/basic"

jq -e '.kind == "8311-was-110-private-vendor-blob-repo"' "$REPO_DIR/vendor_blobs.meta.json" >/dev/null
jq -e '
  .kind == "8311-was-110-bazel-input-handoff"
  and .repository_name == "was110_vendor_blobs"
  and .trust_boundary.remote_execution_proven == false
  and (.bazel_labels | index("@was110_vendor_blobs//:bfw.img"))
' "$REPO_DIR/was110_vendor_blobs.handoff.json" >/dev/null
grep -q 'GF_BAZEL_INJECT_REPOSITORIES' "$REPO_DIR/was110_vendor_blobs.env"
grep -q 'GF_BAZEL_SUBSTRATE_MODE=shared-cache-backed' "$REPO_DIR/was110_vendor_blobs.env"
grep -q -- '--inject_repository=was110_vendor_blobs=' "$REPO_DIR/was110_vendor_blobs.bazelrc"

check_meta() {
  local path="$1" actual expected
  actual=$(sha256sum "$REPO_DIR/$path" | awk '{print $1}')
  expected=$(jq -r --arg path "$path" '.files[$path].sha256 // empty' "$REPO_DIR/vendor_blobs.meta.json")
  [ -n "$expected" ] || { echo "metadata lacks sha256 for $path" >&2; exit 1; }
  if [ "$actual" != "$expected" ]; then
    echo "metadata mismatch for $path: expected=$expected actual=$actual" >&2
    exit 1
  fi
}

check_meta bfw.img
check_meta basic/bootcore.bin
check_meta basic/kernel.bin
check_meta basic/rootfs.img

if [ -f "$REPO_DIR/kernel-bundle.tar" ]; then
  tar -tf "$REPO_DIR/kernel-bundle.tar" | grep -Eq '^(\./)?kernel\.bin$' || {
    echo "kernel-bundle.tar lacks kernel.bin" >&2
    exit 1
  }
  tar -tf "$REPO_DIR/kernel-bundle.tar" | grep -Eq '^(\./)?kernel-build\.json$' || {
    echo "kernel-bundle.tar lacks kernel-build.json" >&2
    exit 1
  }
  check_meta kernel-bundle.tar
fi

echo "vendor blob repo verified: $REPO_DIR"
